### ISSUE TITLE
Help me avoid even more duplication of effort

### ISSUE THREAD

**Issue by C0rn3j** [nyg/wiktionary-to-kindle#1]
Hiya, 
about a week ago I decided to create a project practically like yours, looked things up and did *not* stumble upon this repo.

Today I more or less got most of it working, decided to search once more and found what you created.

I have a bunch of questions and suggestions which I'd highly prefer to discuss in IM instead of forum-like board, would it be possible to get in contact on some IM service? I couldn't find any of your contact info besides the project itself.

Thanks a lot in advance.

Telegram - @C0rn3j
Steam(ID) - c0rn3j
Hangouts - my email is in my github profile

**Comment by nyg** [comment]
Hi,

Sorry for the very late response but I have a lot of things going on IRL. I'll try to contact you via Telegram when I have some free time.

I'm glad someone is interested in this project... have you done anything since you opened this issue? In what languages did you start you project?

Thanks for your patience.
nyg

**Comment by C0rn3j** [comment]
>have you done anything since you opened this issue?

Yeah, I keep working on it.

https://i.imgur.com/oqwwjdA.png

Atm trying to get rid of entries like these and instead turn them into inflections.

![image](https://user-images.githubusercontent.com/1641362/43355469-2aa5bb4a-925d-11e8-982e-64d0120e804e.png)

Am only interested in Norwegian (Nynorsk and Bokmål).

What I initially forgot to mention is that I'm not using an offline parser from the XML dump but rather a scrapper project (WiktionaryParser).

I figured out some things but some things I still need help with(tab2opf, dictionary issues), I'll explain on Telegram when you'll have the time.

**Comment by MaraAlexeev** [comment]
@C0rn3j I stumbled upon  [your gitlab](https://gitlab.com/C0rn3j/NorwegianToEnglishDict) looking for a Bokmål to English dictionary and then found this repo looking for using wiktionary as a word source. It seems both of you have dealing with inflected forms of words on your to do lists. I'm considering forking this and working on that problem. Do you have ideas on how you would solve the issue, if so, I'd be happy to toy around with implementing them if I have time.

(I'm interested in making a Finnish-to-English dictionary and Russian to-English dictionary.)

**Comment by C0rn3j** [comment]
I solved inflections in that project.

It is well documented but the code itself is terrible.
