### ISSUE TITLE
Preserving links from wiktionary?

### ISSUE THREAD

**Issue by circius** [nyg/wiktionary-to-kindle#2]
Hello,

This is a wonderful piece of software. I was able to generate a dictionary for my target language, and all the non-declined terms (singular male nouns and adjectives etc) look lovely. All the declined parts of speech (plurals et al) have as definitions some kind of raw syntax:

`{{feminine plural of|merveilleux|lang=fr}}`

which looks like it's broken markup for a link. Two questions:

1) Is this the normal output of w2k as it stands, or has something gone wrong?
2) Is there any way to make these entries actually link to the non-declined root terms, i.e. the actual semantic definitions?

**Comment by nyg** [comment]
Hello,

Thanks for the kind words ;). This raw syntax is actually the Wiktionary markup used by Wiktionary editors. The double brackets means that it's a template, not a link. In your case the template name is `feminine plural of` (see https://en.wiktionary.org/wiki/Template:feminine_plural_of).

1. So, as it stands, yes this is the normal output for all templates that are not yet handled. A few already are but most aren't.
2. Yes that possible, it can be done in the python code that generates the dictionary but I'm not sure yet on the proper way to do it (there's some information on that in the PDF _Amazon Kindle
Publishing Guidelines_ point 14.4). I have also started to rewrite this part in Java...
