### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by tavibe** [nyg/wiktionary-to-kindle#3]
Hi,

Excellent tool.

I'm now downloading the file frwiktionary-20181020-pages-articles-multistream.xml.bz2  
Can you please confirm this is the right filename (based on your description I think it is).

However in the next step (4) you say that I should run the command 
`java -jar target/wiktionary-to-kindle-1.0.0.jar parse en latest`

Since the fr cannot be dowloaded, how could I parse the fr file? 
Can I pass it as a parameter? Where do I need to place it on the filesystem?

Many thanks

**Comment by nyg** [comment]
Hi,

In step 3, you can specify the language you want to download, so in your case you should have done:

```
java -jar target/wiktionary-to-kindle-1.0.0.jar download fr latest
```

And then in step 4:

```
java -jar target/wiktionary-to-kindle-1.0.0.jar parse fr latest
```

The thing is that JWKTL does not support parsing fr wiktionary dumps... As far as I know they only support English, German and Russian. So executing the above commands will most probably not work.

Also, maybe this is not very clear in the description I wrote but don't confuse source and target language. You can't generate a dictionary whose target language is French. But you can generate a dictionary whose source language is French (and then the target language will be either English, German or Russian).

Hope this helped

**Comment by tavibe** [comment]
Thank you for your reply,
It's a pity that I can't use it for French. I wanted to add other languages as well.

I need more the description of the meaning in french, thus the explanations and definition of the meanings of a particular word, rather than the translations to another language. 

I speak French very well, I do not need necessarily to have certain terms translated in English, the French explanation is good enough.
